services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bot:latest
    container_name: ${COMPOSE_PROJECT_NAME}-bot
    restart: always
    env_file:
      - .env
    ports:
      - ${WEBHOOK_PORT}:${WEBHOOK_PORT}
    networks:
      - app
    depends_on:
      - mysql

  api:
    image: bot:latest
    container_name: ${COMPOSE_PROJECT_NAME}-api
    restart: always
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
    command: python -m api.app
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - app
    depends_on:
      - mysql
  web:
    image: node:20-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-web
    restart: always
    working_dir: /usr/src/app
    env_file:
      - .env
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    networks:
      - app
    depends_on:
      - api
    volumes:
      - ./web:/usr/src/app
    command: sh -c "npm install && npm run dev"

  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    networks:
      - app
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password




  mysqlbackup:
    container_name: ${COMPOSE_PROJECT_NAME}-mysqlbackup
    image: databack/mysql-backup
    restart: always
    volumes:
      - backups-data:/db
    networks:
      - app
    depends_on:
      - mysql
    environment:
      - DB_SERVER=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAMES=${DB_NAME}
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0300
      - DB_CLEANUP_TIME=2880
      - COMPRESSION=gzip


  migrator:
    image: bot:latest
    container_name: ${COMPOSE_PROJECT_NAME}-migrator
    restart: "on-failure"
    command: alembic upgrade head
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - bot
    volumes:
      - ./migrations:/usr/src/app/migrations

networks:
  app:
    driver: bridge

volumes:
  backups-data: {}
  mysql-data: {}
